In [1]:
import numpy as np
import pandas as pd

from pandas.io import gbq

### Choose one playlist to experiment with features on

* **playlist_id** 4ykrONBhOgPr4sMhAVCoPx

* **name** Hip Hop Hits
	
* **owner** digster.fm

* **description** A hip hop playlist of the most wanted hip hop hits featuring ScHoolboy Q, Drake, J. Cole and more!

* 830,000 **followers**

* 85 **tracks**, 238 **albums**, 121 **artist**

In [4]:
get_session_data = """
SELECT * FROM `umg-comm-tech-dev.playlist_sequencing.user_session_data` WHERE playlist_id = '4ykrONBhOgPr4sMhAVCoPx' 
"""

In [5]:
df_sess = gbq.read_gbq(get_session_data, project_id='umg-comm-tech-dev', dialect='standard')

In [7]:
df_sess.describe(include='all')

,user_id,playlist_id,isrc,user_country_code,user_gender,user_age_group,stream_duration,stream_source,device_type,os_name,...,partner_user_type,revenue_model,consumer_group,consumer_group_detail,partner_report_date,utc_timestamp_offset,offline_timestamp,total_isrc_count,completed_isrc_count,session_id
count,52485,52485,52485,52485,52485,52485,52485.000000,52485,52485,52485,...,52485,52485,52485,52485,52485,52485,52485,52485.000000,52485.000000,52485
unique,4948,1,82,66,3,8,NaN,1,6,7,...,4,2,3,8,7,21,12165,NaN,NaN,42
top,7dfba43c6e1bab567d85ca8f89812ab2d544d80dfc4f5c...,4ykrONBhOgPr4sMhAVCoPx,USUM71912330,US,male,25-34,NaN,others_playlist,personal computer,Windows,...,paid,Premium,Paid,Ad-Funded,2019-08-13 00:00:00,-04:00,[2019-08-13 17:44:00+00:00],NaN,NaN,[1]
freq,432,52485,3032,35302,34796,21509,NaN,52485,21777,22144,...,29789,30436,30104,22049,14269,18268,40,NaN,NaN,50288
first,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2019-08-11 00:00:00,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2019-08-17 00:00:00,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,165.380547,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.059026,0.778965,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,65.845844,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.682022,0.834334,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,30.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,131.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,174.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,205.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,122.000000,122.000000,NaN

In [8]:
get_pl_tracks_data = """
SELECT * FROM `umg-comm-tech-dev.playlist_sequencing.playlist_track_listings` WHERE playlist_id = '4ykrONBhOgPr4sMhAVCoPx' 
"""

In [9]:
df_pl_tracks = gbq.read_gbq(get_pl_tracks_data, project_id='umg-comm-tech-dev', dialect='standard')

In [11]:
df_pl_tracks.describe(include='all')

,playlist_id,playlist_name,playlist_owner,playlist_description,min_follower_count,max_follower_count,maxpos,nalbums,nartists,min_track_date,max_track_date,isrc,min_track_position,max_track_position,avg_track_position,std_track_position,track_artist,track_title,track_add_by
count,175,175,175,175,175.0,175.0,175.0,175.0,175.0,175,175,175,175.000000,175.000000,175.000000,175.000000,175,175,175
unique,1,1,1,1,NaN,NaN,NaN,NaN,NaN,59,23,170,NaN,NaN,NaN,NaN,93,175,1
top,4ykrONBhOgPr4sMhAVCoPx,Hip Hop Hits,digster.fm,A hip hop playlist of the most wanted hip hop ...,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00,2019-06-30 00:00:00,QMCE31902212,NaN,NaN,NaN,NaN,Drake,"100 Bands (feat. Quavo, 21 Savage, Meek Mill &...",digster.fm
freq,175,175,175,175,NaN,NaN,NaN,NaN,NaN,43,50,2,NaN,NaN,NaN,NaN,10,1,175
first,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01 00:00:00,2019-01-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
last,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-29 00:00:00,2019-06-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,18.405714,35.862857,26.331101,5.600075,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,13.140749,16.746368,13.927886,4.726386,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,1.000000,2.000000,1.125000,0.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,7.000000,24.000000,14.960366,1.653271,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,17.000000,37.000000,25.224138,4.442120,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,26.500000,48.500000,36.668557,8.337416,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,827504.0,831446.0,85.0,238.0,121.0,NaN,NaN,NaN,58.000000,68.000000,64.428571,22.712180,NaN,NaN,NaN