In [1]:
import pandas as pd
from pandas.io import gbq

In [2]:
get_data_sql = """
SELECT * FROM `umg-comm-tech-dev.diaspora.indian_top_rep`"""

In [3]:
data = gbq.read_gbq(get_data_sql, project_id='umg-comm-tech-dev', dialect = 'standard')

In [4]:
data.head()

,user_count,streams,user_dma_number,user_dma_name,user_country_code,user_country_name,stream_country_code,stream_country_name,user_region_code,user_postal_code,...,partner_user_type,revenue_model,consumer_group,consumer_group_detail,engagement_style,isrc,content_type,upc,source_uri,stream_source
0,1,2,None,None,None,None,IN,India,None,None,...,None,None,None,None,Lean Forward,INUM71800013,Top 3 VYRL Established,00602567781806,,collection
1,1,1,None,None,None,None,IN,India,None,None,...,None,None,None,None,Lean Forward,INUM71800041,Top 3 VYRL Established,00602577426193,,collection
2,1,1,None,None,None,None,IN,India,None,None,...,None,None,None,None,Lean Back,INUM71800041,Top 3 VYRL Established,00602577426193,,radio
3,1,1,511,"Washington, DC (Hagrstwn)",US,United States,US,United States,,114,...,partner,Premium,Paid,Bundle,Lean Back,INUM71800013,Top 3 VYRL Established,00602567781806,,radio
4,1,4,548,West Palm Beach-Ft. Pierce,US,United States,US,United States,,,...,partner,Premium,Paid,Bundle,Lean Forward,INUM71400256,Bollywood Catalogue,00602537882793,,collection

In [5]:
by_columns = ['stream_country_code','stream_country_name','user_dma_number',
  'user_dma_name']

In [6]:
data_by_geo = data.groupby(by=by_columns)